[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "KeepsakePort"
versionNumber = "3.0.0"
description = "Porting Keepsakes over from Hades 1 to Hades 2."
websiteUrl = "https://github.com/zanncdwbl/zannc-KeepsakePort"
containsNsfwContent = false

[package.dependencies]
zannc-SharedKeepsakePort = "1.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# [[build.copy]]
# source = "./packages"
# target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = ["hades-ii"]

[publish.categories]
hades-ii = ["mods"]
